services:
  web:
    image: node:20-bullseye-slim
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=development
